allprojects {
    afterEvaluate {
        tasks.withType(JavaCompile).configureEach {
            options.release.set(17)
            sourceCompatibility = '17'
            targetCompatibility = '17'
        }
        plugins.withId('java') {
            java { toolchain { languageVersion = JavaLanguageVersion.of(17) } }
        }
    }
}
